"""
Django settings for pexproject project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__))
Temp_Path = os.path.realpath('.')

# Other settings...
TEMPLATE_DIRS = (
    PROJECT_ROOT +"/templates/",
)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '92esi-0)q&l-mn)-env37sufs@r0%0h2^^)kaqp4i42r9%lr&m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['pexportal.com']

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles', 
    'django.contrib.humanize',
    'pexproject',
    'oauth2',
    'social_auth',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
       
)

ROOT_URLCONF ='pexproject.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [PROJECT_ROOT +"/templates/"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pexproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'pex',
#         'USER': 'root',
#         'PASSWORD': '1jyT382PWzYP',
#         'default-character-set' : 'utf8',
#         'host': 'localhost',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

#log file 
'''
LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'formatters': {
        'standard': {
            'format' : "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            'datefmt' : "%d/%b/%Y %H:%M:%S"
        },
    },
    'handlers': {
        'null': {
            'level':'DEBUG',
            'class':'django.utils.log.NullHandler',
        },
        'logfile': {
            'level':'DEBUG',
            'class':'logging.handlers.RotatingFileHandler',
            'filename': "logfile",
            'maxBytes': 50000,
            'backupCount': 2,
            'formatter': 'standard',
        },
        'console':{
            'level':'INFO',
            'class':'logging.StreamHandler',
            'formatter': 'standard'
        },
    },
        },
        'pexproject': {
            'handlers': ['console', 'logfile'],
            'level': 'DEBUG',
        },
    }
}
'''
TEMPLATE_CONTEXT_PROCESSORS = (                                         
    'django.core.context_processors.request',
    'social.apps.django_app.context_processors.backends',
    'django.contrib.auth.context_processors.auth',
    'social.apps.django_app.context_processors.login_redirect',
    'django.contrib.auth.backends.ModelBackend',
    'social_auth.context_processors.social_auth_by_name_backends',
    'social_auth.context_processors.social_auth_backends',
    'social_auth.context_processors.social_auth_by_type_backends',
    'social_auth.context_processors.social_auth_login_redirect',
    )

AUTHENTICATION_BACKENDS = (
    'social_auth.backends.twitter.TwitterBackend',
    'social_auth.backends.facebook.FacebookBackend',
    'social_auth.backends.google.GoogleOAuthBackend',
    'social_auth.backends.google.GoogleOAuth2Backend',
    'social_auth.backends.google.GoogleBackend',
    'social_auth.backends.OpenIDBackend',
    #'social_auth..backends.email.EmailAuth',
    'django.contrib.auth.backends.ModelBackend',
)
'''
SOCIAL_AUTH_PIPELINE = (
    #'social_auth.backends.pipeline.user.create_user',
    #'social_auth.backends.pipeline.social.social_auth_user',
    #'social_auth.backends.pipeline.social.associate_user',
    #'social_auth.backends.pipeline.social.load_extra_data',
    #'social_auth.backends.pipeline.user.update_user_details'
)
'''
FACEBOOK_EXTENDED_PERMISSIONS = ['email']
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
FACEBOOK_PROFILE_EXTRA_PARAMS = {'fields': 'id,name,email,first_name,last_name','locale': 'ru_RU'}
#SOCIAL_AUTH_FACEBOOK_SCOPE = ['email','public_profile','username']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    'fields': 'id,name,email',
}
SOCIAL_AUTH_FIELDS_STORED_IN_SESSION = ['username']
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
FACEBOOK_APP_ID='423944854478305'
FACEBOOK_API_SECRET='cb583c182bbf2fe402ff5ea7fabfd8ec'
SESSION_SERIALIZER='django.contrib.sessions.serializers.PickleSerializer'


SOCIAL_AUTH_ENABLED_BACKENDS = 'google'
SOCIAL_AUTH_USER_MODEL = 'pexproject.User'
AUTH_USER_MODEL = 'pexproject.User'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/'
SOCIAL_AUTH_NEW_USER_REDIRECT_URL = '/login/'
SOCIAL_AUTH_USERNAME_IS_FULL_EMAIL = True
#SOCIAL_AUTH_PROTECTED_USER_FIELDS = ['email']
GOOGLE_OAUTH2_CLIENT_ID='975229172193-7rl5ikgl1cu79htkdf1pu9keqjp92iej.apps.googleusercontent.com'
GOOGLE_OAUTH2_CLIENT_SECRET='bj53Bjtmt4NI6WfTd7ehapm8'
GOOGLE_OAUTH2_SCOPE = ['https://www.googleapis.com/auth/userinfo.email',]
#GOOGLE_WHITE_LISTED_DOMAINS = ['pexportal.com']
LANGUAGE_CODE = 'en-us'
EMAIL_HOST = 'localhost'
TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

#mail_to = "info@pexportal.com"
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_ROOT = os.path.join(PROJECT_ROOT, 'static/')
STATIC_URL = '/static/'
#STATICFILES_DIRS = (
#  os.path.join(PROJECT_ROOT, 'static')
#)
